version: '3'
services:
  db:
    image: postgis/postgis:14-3.2  # This uses a PostGIS-enabled image
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
