services:
  db:
    image: postgis/postgis:14-3.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: travel
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

  # New app-db service (shared models and migrations)
  app-db:
    build:
      context: .
      dockerfile: packages/app-db/Dockerfile # Adjust the path to your 'app' package Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: travel
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network
    command: yarn migration:run # Run migrations after building

  travel-server:
    build:
      context: .
      dockerfile: packages/travel-server/Dockerfile
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: travel
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - app-db # Ensure app-db builds first and runs migrations
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
